//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_S_H
#define METASPRITE_S_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define S_TILE_ORIGIN 0
#define S_TILE_H 8
#define S_WIDTH 32
#define S_HEIGHT 32
#define S_TILE_COUNT 9
#define S_PIVOT_X 16
#define S_PIVOT_Y 16
#define S_PIVOT_W 32
#define S_PIVOT_H 32

BANKREF_EXTERN(S)

extern const palette_color_t S_palettes[4];
extern const uint8_t S_tiles[144];

extern const metasprite_t* const S_metasprites[1];

#endif