//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_SR_H
#define METASPRITE_SR_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define SR_TILE_ORIGIN 0
#define SR_TILE_H 8
#define SR_WIDTH 32
#define SR_HEIGHT 32
#define SR_TILE_COUNT 2
#define SR_PIVOT_X 16
#define SR_PIVOT_Y 16
#define SR_PIVOT_W 32
#define SR_PIVOT_H 32

BANKREF_EXTERN(SR)

extern const palette_color_t SR_palettes[4];
extern const uint8_t SR_tiles[32];

extern const metasprite_t* const SR_metasprites[1];

#endif