//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_soic_c_H
#define METASPRITE_soic_c_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define soic_c_TILE_ORIGIN 0
#define soic_c_TILE_H 8
#define soic_c_WIDTH 16
#define soic_c_HEIGHT 32
#define soic_c_TILE_COUNT 8
#define soic_c_PIVOT_X 8
#define soic_c_PIVOT_Y 16
#define soic_c_PIVOT_W 16
#define soic_c_PIVOT_H 32

BANKREF_EXTERN(soic_c)

extern const palette_color_t soic_c_palettes[8];
extern const uint8_t soic_c_tiles[128];

extern const metasprite_t* const soic_c_metasprites[1];

#endif