int16_t x = 20;
int16_t y = 50;
uint8_t direction;
//uint8_t woomy = 0;
int16_t scrollpositionlast = 20;
uint8_t tileup;
uint8_t tiledown;
uint8_t tileleft;
uint8_t tileright;
uint8_t tilecenter;
int8_t speedy;
int8_t speedx;
int16_t calcx = 20*16;
int16_t displayval;
//int8_t last5mod = 0;
//int8_t last7mod = 0;
//int8_t cur5mod = 0;
//int8_t cur7mod = 0;
int16_t lastscrollwritepos;
int16_t lastx = 1;
int16_t backwards_lastx;
int16_t backwards_pixels;
int16_t oldcalcx;
int8_t waterfall_frame;
int8_t waterfall_frame2;
int8_t jumpaccel;
//int8_t jumpaccel_lower = 0;
//int8_t speedx_od = 0;
int8_t jumpavailable = 1;
uint8_t ring_count;
char text_time[15];
uint8_t ringframe;
int8_t lasttime = -1;
uint8_t loadd;
uint16_t poleload;
uint16_t swdrerd;
uint8_t finish_frames_deddeded;
int8_t display_x;
int8_t fake_right;
_Bool ringsprite_used[10];
static const uint8_t X_RING_OFFSET = 28;
static const uint8_t Y_RING_OFFSET = 16;
static const uint8_t ringindexsubtract = 30;
uint8_t tilex;
uint8_t tiley;
uint8_t frames;
uint8_t seconds;
uint8_t minutes;
uint8_t lastringcount;