//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W10R_H
#define METASPRITE_W10R_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W10R_TILE_ORIGIN 0
#define W10R_TILE_H 8
#define W10R_WIDTH 32
#define W10R_HEIGHT 32
#define W10R_TILE_COUNT 3
#define W10R_PIVOT_X 16
#define W10R_PIVOT_Y 16
#define W10R_PIVOT_W 32
#define W10R_PIVOT_H 32

BANKREF_EXTERN(W10R)

extern const palette_color_t W10R_palettes[4];
extern const uint8_t W10R_tiles[48];

extern const metasprite_t* const W10R_metasprites[1];

#endif