//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W11R_H
#define METASPRITE_W11R_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W11R_TILE_ORIGIN 0
#define W11R_TILE_H 8
#define W11R_WIDTH 32
#define W11R_HEIGHT 32
#define W11R_TILE_COUNT 5
#define W11R_PIVOT_X 16
#define W11R_PIVOT_Y 16
#define W11R_PIVOT_W 32
#define W11R_PIVOT_H 32

BANKREF_EXTERN(W11R)

extern const palette_color_t W11R_palettes[4];
extern const uint8_t W11R_tiles[80];

extern const metasprite_t* const W11R_metasprites[1];

#endif