//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W12R_H
#define METASPRITE_W12R_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W12R_TILE_ORIGIN 0
#define W12R_TILE_H 8
#define W12R_WIDTH 32
#define W12R_HEIGHT 32
#define W12R_TILE_COUNT 6
#define W12R_PIVOT_X 16
#define W12R_PIVOT_Y 16
#define W12R_PIVOT_W 32
#define W12R_PIVOT_H 32

BANKREF_EXTERN(W12R)

extern const palette_color_t W12R_palettes[4];
extern const uint8_t W12R_tiles[96];

extern const metasprite_t* const W12R_metasprites[1];

#endif