//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(W14R)

const palette_color_t W14R_palettes[4] = {
	RGB8(0, 0, 0), RGB8(252, 0, 0), RGB8(0, 0, 1), RGB8(0, 0, 0)
};

const uint8_t W14R_tiles[32] = {
	0x00,0x00,0x00,0x00,0x00,0x00,0x03,0x00,0x07,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x60,0x00,0x30,0x00,0x00,0x00,0xc0,0x00,0x00,0x00,0x30,0x00,0x78,0x00,0x00,0x00
};

const metasprite_t W14R_metasprite0[] = {
	METASPR_ITEM(8, -8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_TERM
};

const metasprite_t* const W14R_metasprites[1] = {
	W14R_metasprite0
};
