//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W1R_H
#define METASPRITE_W1R_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W1R_TILE_ORIGIN 0
#define W1R_TILE_H 8
#define W1R_WIDTH 32
#define W1R_HEIGHT 32
#define W1R_TILE_COUNT 4
#define W1R_PIVOT_X 16
#define W1R_PIVOT_Y 16
#define W1R_PIVOT_W 32
#define W1R_PIVOT_H 32

BANKREF_EXTERN(W1R)

extern const palette_color_t W1R_palettes[4];
extern const uint8_t W1R_tiles[64];

extern const metasprite_t* const W1R_metasprites[1];

#endif