//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W2R_H
#define METASPRITE_W2R_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W2R_TILE_ORIGIN 0
#define W2R_TILE_H 8
#define W2R_WIDTH 32
#define W2R_HEIGHT 32
#define W2R_TILE_COUNT 3
#define W2R_PIVOT_X 16
#define W2R_PIVOT_Y 16
#define W2R_PIVOT_W 32
#define W2R_PIVOT_H 32

BANKREF_EXTERN(W2R)

extern const palette_color_t W2R_palettes[4];
extern const uint8_t W2R_tiles[48];

extern const metasprite_t* const W2R_metasprites[1];

#endif