//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W6R_H
#define METASPRITE_W6R_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W6R_TILE_ORIGIN 0
#define W6R_TILE_H 8
#define W6R_WIDTH 32
#define W6R_HEIGHT 32
#define W6R_TILE_COUNT 2
#define W6R_PIVOT_X 16
#define W6R_PIVOT_Y 16
#define W6R_PIVOT_W 32
#define W6R_PIVOT_H 32

BANKREF_EXTERN(W6R)

extern const palette_color_t W6R_palettes[4];
extern const uint8_t W6R_tiles[32];

extern const metasprite_t* const W6R_metasprites[1];

#endif