//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(W6R)

const palette_color_t W6R_palettes[4] = {
	RGB8(0, 0, 0), RGB8(252, 0, 0), RGB8(0, 0, 0), RGB8(0, 0, 0)
};

const uint8_t W6R_tiles[32] = {
	0x00,0x00,0x00,0x00,0x00,0x00,0x03,0x00,0x07,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x60,0x00,0x30,0x00,0x00,0x00,0x90,0x00,0x38,0x00,0x00,0x00,0x00,0x00,0x00,0x00
};

const metasprite_t W6R_metasprite0[] = {
	METASPR_ITEM(8, -8, 0, 0), METASPR_ITEM(0, 8, 1, 0), METASPR_TERM
};

const metasprite_t* const W6R_metasprites[1] = {
	W6R_metasprite0
};
