//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W9R_H
#define METASPRITE_W9R_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W9R_TILE_ORIGIN 0
#define W9R_TILE_H 8
#define W9R_WIDTH 32
#define W9R_HEIGHT 32
#define W9R_TILE_COUNT 4
#define W9R_PIVOT_X 16
#define W9R_PIVOT_Y 16
#define W9R_PIVOT_W 32
#define W9R_PIVOT_H 32

BANKREF_EXTERN(W9R)

extern const palette_color_t W9R_palettes[4];
extern const uint8_t W9R_tiles[64];

extern const metasprite_t* const W9R_metasprites[1];

#endif