//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W1_H
#define METASPRITE_W1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W1_TILE_ORIGIN 0
#define W1_TILE_H 8
#define W1_WIDTH 32
#define W1_HEIGHT 32
#define W1_TILE_COUNT 13
#define W1_PIVOT_X 16
#define W1_PIVOT_Y 16
#define W1_PIVOT_W 32
#define W1_PIVOT_H 32

BANKREF_EXTERN(W1)

extern const palette_color_t W1_palettes[4];
extern const uint8_t W1_tiles[208];

extern const metasprite_t* const W1_metasprites[1];

#endif