//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W10_H
#define METASPRITE_W10_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W10_TILE_ORIGIN 0
#define W10_TILE_H 8
#define W10_WIDTH 32
#define W10_HEIGHT 32
#define W10_TILE_COUNT 9
#define W10_PIVOT_X 16
#define W10_PIVOT_Y 16
#define W10_PIVOT_W 32
#define W10_PIVOT_H 32

BANKREF_EXTERN(W10)

extern const palette_color_t W10_palettes[4];
extern const uint8_t W10_tiles[144];

extern const metasprite_t* const W10_metasprites[1];

#endif