//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W11_H
#define METASPRITE_W11_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W11_TILE_ORIGIN 0
#define W11_TILE_H 8
#define W11_WIDTH 32
#define W11_HEIGHT 32
#define W11_TILE_COUNT 12
#define W11_PIVOT_X 16
#define W11_PIVOT_Y 16
#define W11_PIVOT_W 32
#define W11_PIVOT_H 32

BANKREF_EXTERN(W11)

extern const palette_color_t W11_palettes[4];
extern const uint8_t W11_tiles[192];

extern const metasprite_t* const W11_metasprites[1];

#endif