//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W12_H
#define METASPRITE_W12_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W12_TILE_ORIGIN 0
#define W12_TILE_H 8
#define W12_WIDTH 32
#define W12_HEIGHT 32
#define W12_TILE_COUNT 13
#define W12_PIVOT_X 16
#define W12_PIVOT_Y 16
#define W12_PIVOT_W 32
#define W12_PIVOT_H 32

BANKREF_EXTERN(W12)

extern const palette_color_t W12_palettes[4];
extern const uint8_t W12_tiles[208];

extern const metasprite_t* const W12_metasprites[1];

#endif