//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W13_H
#define METASPRITE_W13_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W13_TILE_ORIGIN 0
#define W13_TILE_H 8
#define W13_WIDTH 32
#define W13_HEIGHT 32
#define W13_TILE_COUNT 13
#define W13_PIVOT_X 16
#define W13_PIVOT_Y 16
#define W13_PIVOT_W 32
#define W13_PIVOT_H 32

BANKREF_EXTERN(W13)

extern const palette_color_t W13_palettes[4];
extern const uint8_t W13_tiles[208];

extern const metasprite_t* const W13_metasprites[1];

#endif