//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W15_H
#define METASPRITE_W15_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W15_TILE_ORIGIN 0
#define W15_TILE_H 8
#define W15_WIDTH 32
#define W15_HEIGHT 32
#define W15_TILE_COUNT 12
#define W15_PIVOT_X 16
#define W15_PIVOT_Y 16
#define W15_PIVOT_W 32
#define W15_PIVOT_H 32

BANKREF_EXTERN(W15)

extern const palette_color_t W15_palettes[4];
extern const uint8_t W15_tiles[192];

extern const metasprite_t* const W15_metasprites[1];

#endif