//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W2_H
#define METASPRITE_W2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W2_TILE_ORIGIN 0
#define W2_TILE_H 8
#define W2_WIDTH 32
#define W2_HEIGHT 32
#define W2_TILE_COUNT 9
#define W2_PIVOT_X 16
#define W2_PIVOT_Y 16
#define W2_PIVOT_W 32
#define W2_PIVOT_H 32

BANKREF_EXTERN(W2)

extern const palette_color_t W2_palettes[4];
extern const uint8_t W2_tiles[144];

extern const metasprite_t* const W2_metasprites[1];

#endif