//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W3_H
#define METASPRITE_W3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W3_TILE_ORIGIN 0
#define W3_TILE_H 8
#define W3_WIDTH 32
#define W3_HEIGHT 32
#define W3_TILE_COUNT 12
#define W3_PIVOT_X 16
#define W3_PIVOT_Y 16
#define W3_PIVOT_W 32
#define W3_PIVOT_H 32

BANKREF_EXTERN(W3)

extern const palette_color_t W3_palettes[4];
extern const uint8_t W3_tiles[192];

extern const metasprite_t* const W3_metasprites[1];

#endif