//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W4_H
#define METASPRITE_W4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W4_TILE_ORIGIN 0
#define W4_TILE_H 8
#define W4_WIDTH 32
#define W4_HEIGHT 32
#define W4_TILE_COUNT 13
#define W4_PIVOT_X 16
#define W4_PIVOT_Y 16
#define W4_PIVOT_W 32
#define W4_PIVOT_H 32

BANKREF_EXTERN(W4)

extern const palette_color_t W4_palettes[4];
extern const uint8_t W4_tiles[208];

extern const metasprite_t* const W4_metasprites[1];

#endif