//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W5_H
#define METASPRITE_W5_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W5_TILE_ORIGIN 0
#define W5_TILE_H 8
#define W5_WIDTH 32
#define W5_HEIGHT 32
#define W5_TILE_COUNT 13
#define W5_PIVOT_X 16
#define W5_PIVOT_Y 16
#define W5_PIVOT_W 32
#define W5_PIVOT_H 32

BANKREF_EXTERN(W5)

extern const palette_color_t W5_palettes[4];
extern const uint8_t W5_tiles[208];

extern const metasprite_t* const W5_metasprites[1];

#endif