//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W6_H
#define METASPRITE_W6_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W6_TILE_ORIGIN 0
#define W6_TILE_H 8
#define W6_WIDTH 32
#define W6_HEIGHT 32
#define W6_TILE_COUNT 9
#define W6_PIVOT_X 16
#define W6_PIVOT_Y 16
#define W6_PIVOT_W 32
#define W6_PIVOT_H 32

BANKREF_EXTERN(W6)

extern const palette_color_t W6_palettes[4];
extern const uint8_t W6_tiles[144];

extern const metasprite_t* const W6_metasprites[1];

#endif