//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W7_H
#define METASPRITE_W7_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W7_TILE_ORIGIN 0
#define W7_TILE_H 8
#define W7_WIDTH 32
#define W7_HEIGHT 32
#define W7_TILE_COUNT 12
#define W7_PIVOT_X 16
#define W7_PIVOT_Y 16
#define W7_PIVOT_W 32
#define W7_PIVOT_H 32

BANKREF_EXTERN(W7)

extern const palette_color_t W7_palettes[4];
extern const uint8_t W7_tiles[192];

extern const metasprite_t* const W7_metasprites[1];

#endif