//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W8_H
#define METASPRITE_W8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W8_TILE_ORIGIN 0
#define W8_TILE_H 8
#define W8_WIDTH 32
#define W8_HEIGHT 32
#define W8_TILE_COUNT 13
#define W8_PIVOT_X 16
#define W8_PIVOT_Y 16
#define W8_PIVOT_W 32
#define W8_PIVOT_H 32

BANKREF_EXTERN(W8)

extern const palette_color_t W8_palettes[4];
extern const uint8_t W8_tiles[208];

extern const metasprite_t* const W8_metasprites[1];

#endif