//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_W9_H
#define METASPRITE_W9_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define W9_TILE_ORIGIN 0
#define W9_TILE_H 8
#define W9_WIDTH 32
#define W9_HEIGHT 32
#define W9_TILE_COUNT 13
#define W9_PIVOT_X 16
#define W9_PIVOT_Y 16
#define W9_PIVOT_W 32
#define W9_PIVOT_H 32

BANKREF_EXTERN(W9)

extern const palette_color_t W9_palettes[4];
extern const uint8_t W9_tiles[208];

extern const metasprite_t* const W9_metasprites[1];

#endif