/*

Filename: numtiles_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 11 x 1
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define numtiles_map_width 11
#define numtiles_map_height 1
#define numtiles_map_tiles 11
#define numtiles_map_bytes 11

extern unsigned char numtiles_map[];
extern unsigned char numtiles_map_attr[];

