/*

Filename: numtiles_map.c 

Map SOURCE File 

 Info:
   Section       :
   Bank          : 0
   Map size      : 11 x 1
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define numtiles_map_width 11
#define numtiles_map_height 1
#define numtiles_map_tiles 11
#define numtiles_map_bytes 11


const unsigned char numtiles_map[11] = 
{
   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, };


const unsigned char numtiles_map_attr[11] = 
{
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, };
