/*

 EGG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __egg_h_INCLUDE
#define __egg_h_INCLUDE

#define eggWidth 3
#define eggHeight 3
#define eggBank 0

#define egg eggPLN0
extern const unsigned char eggPLN0[];
extern const unsigned char eggPLN1[];

#endif

/* End of EGG.H */
