/*

 EGG.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define eggWidth 3
#define eggHeight 3
#define eggBank 0

const unsigned char eggPLN0[] =
{
  0x1F,0x21,0x1F,0x20,0x22,0x20,0x1E,0x33,0x1E
};

const unsigned char eggPLN1[] =
{
  0x01,0x01,0x21,0x01,0x01,0x21,0x02,0x07,0x02
};

/* End of EGG.C */
