/*

 EGG_ROTATED.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __egg_rotated_h_INCLUDE
#define __egg_rotated_h_INCLUDE

#define egg_rotatedWidth 3
#define egg_rotatedHeight 3
#define egg_rotatedBank 0

#define egg_rotated egg_rotatedPLN0
extern const unsigned char egg_rotatedPLN0[];
extern const unsigned char egg_rotatedPLN1[];

#endif

/* End of EGG_ROTATED.H */
