/*

 EGG_ROTATED_MIRRORED.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __egg_rotated_mirrored_h_INCLUDE
#define __egg_rotated_mirrored_h_INCLUDE

#define egg_rotated_mirroredWidth 3
#define egg_rotated_mirroredHeight 3
#define egg_rotated_mirroredBank 0

#define egg_rotated_mirrored egg_rotated_mirroredPLN0
extern const unsigned char egg_rotated_mirroredPLN0[];
extern const unsigned char egg_rotated_mirroredPLN1[];

#endif

/* End of EGG_ROTATED_MIRRORED.H */
