/*

 EGG_ROTATED_MIRRORED.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define egg_rotated_mirroredWidth 3
#define egg_rotated_mirroredHeight 3
#define egg_rotated_mirroredBank 0

const unsigned char egg_rotated_mirroredPLN0[] =
{
  0x35,0x36,0x37,0x38,0x39,0x3A,0x1E,0x33,0x34
};

const unsigned char egg_rotated_mirroredPLN1[] =
{
  0x01,0x01,0x01,0x01,0x01,0x01,0x02,0x27,0x01
};

/* End of EGG_ROTATED_MIRRORED.C */
