/*

 EGG_ROTATED.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define egg_rotatedWidth 3
#define egg_rotatedHeight 3
#define egg_rotatedBank 0

const unsigned char egg_rotatedPLN0[] =
{
  0x37,0x36,0x35,0x3A,0x39,0x38,0x34,0x33,0x1E
};

const unsigned char egg_rotatedPLN1[] =
{
  0x21,0x21,0x21,0x21,0x21,0x21,0x21,0x27,0x02
};

/* End of EGG_ROTATED.C */
