/*

 EMPTY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __empty_h_INCLUDE
#define __empty_h_INCLUDE

#define emptyWidth 3
#define emptyHeight 3
#define emptyBank 0

#define empty emptyPLN0
extern const unsigned char emptyPLN0[];
extern const unsigned char emptyPLN1[];

#endif

/* End of EMPTY.H */
