/*

 EMPTY_ROTATED.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define empty_rotatedWidth 3
#define empty_rotatedHeight 3
#define empty_rotatedBank 0

const unsigned char empty_rotatedPLN0[] =
{
  0x3B,0x3C,0x3D,0x3E,0x3F,0x3A,0x1E,0x33,0x34
};

const unsigned char empty_rotatedPLN1[] =
{
  0x01,0x01,0x01,0x01,0x01,0x01,0x02,0x07,0x01
};

/* End of EMPTY_ROTATED.C */
