/*

 EMPTY_ROTATED.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __empty_rotated_h_INCLUDE
#define __empty_rotated_h_INCLUDE

#define empty_rotatedWidth 3
#define empty_rotatedHeight 3
#define empty_rotatedBank 0

#define empty_rotated empty_rotatedPLN0
extern const unsigned char empty_rotatedPLN0[];
extern const unsigned char empty_rotatedPLN1[];

#endif

/* End of EMPTY_ROTATED.H */
