/*

 EMPTY_ROTATED_MIRRORED.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define empty_rotated_mirroredWidth 3
#define empty_rotated_mirroredHeight 3
#define empty_rotated_mirroredBank 0

const unsigned char empty_rotated_mirroredPLN0[] =
{
  0x3D,0x3C,0x3B,0x3A,0x3F,0x3E,0x34,0x33,0x1E
};

const unsigned char empty_rotated_mirroredPLN1[] =
{
  0x21,0x21,0x21,0x21,0x21,0x21,0x21,0x27,0x02
};

/* End of EMPTY_ROTATED_MIRRORED.C */
