/*

 POLE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define poleWidth 3
#define poleHeight 3
#define poleBank 0

const unsigned char polePLN0[] =
{
  0x1E,0x33,0x1E,0x1E,0x33,0x1E,0x1E,0x33,0x1E
};

const unsigned char polePLN1[] =
{
  0x02,0x07,0x02,0x02,0x07,0x02,0x02,0x07,0x02
};

/* End of POLE.C */
