/*

 POLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __pole_h_INCLUDE
#define __pole_h_INCLUDE

#define poleWidth 3
#define poleHeight 3
#define poleBank 0

#define pole polePLN0
extern const unsigned char polePLN0[];
extern const unsigned char polePLN1[];

#endif

/* End of POLE.H */
