/*

 SONIC_ROTATED.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __sonic_rotated_h_INCLUDE
#define __sonic_rotated_h_INCLUDE

#define sonic_rotatedWidth 3
#define sonic_rotatedHeight 3
#define sonic_rotatedBank 0

#define sonic_rotated sonic_rotatedPLN0
extern const unsigned char sonic_rotatedPLN0[];
extern const unsigned char sonic_rotatedPLN1[];

#endif

/* End of SONIC_ROTATED.H */
