/*

 SONICFINISHED.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define sonicfinishedWidth 3
#define sonicfinishedHeight 3
#define sonicfinishedBank 0

const unsigned char sonicfinishedPLN0[] =
{
  0x26,0x28,0x2A,0x27,0x29,0x2B,0x1E,0x33,0x1E
};

const unsigned char sonicfinishedPLN1[] =
{
  0x01,0x01,0x01,0x01,0x01,0x01,0x02,0x07,0x02
};

/* End of SONICFINISHED.C */
