/*

 SONIC_ROTATED.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define sonic_rotatedWidth 3
#define sonic_rotatedHeight 3
#define sonic_rotatedBank 0

const unsigned char sonic_rotatedPLN0[] =
{
  0x2E,0x2D,0x2C,0x31,0x30,0x2F,0x34,0x33,0x1E
};

const unsigned char sonic_rotatedPLN1[] =
{
  0x21,0x21,0x21,0x21,0x21,0x21,0x21,0x27,0x02
};

/* End of SONIC_ROTATED.C */
