/*

 SONIC_ROTATED_MIRRORED.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 30
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __sonic_rotated_mirrored_h_INCLUDE
#define __sonic_rotated_mirrored_h_INCLUDE

#define empty_rotated_mirroredWidth 3
#define empty_rotated_mirroredHeight 3
#define empty_rotated_mirroredBank 0

#define empty_rotated_mirrored empty_rotated_mirroredPLN0
extern const unsigned char empty_rotated_mirroredPLN0[];
extern const unsigned char empty_rotated_mirroredPLN1[];

#endif

/* End of SONIC_ROTATED_MIRRORED.H */
