/*

 EXPORT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Export_h_INCLUDE
#define __Export_h_INCLUDE

/* Bank of tiles. */
#define ringspriteBank 0

/* Super Gameboy palette 0 */
#define ringspriteSGBPal0c0 6076
#define ringspriteSGBPal0c1 8935
#define ringspriteSGBPal0c2 6596
#define ringspriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ringspriteSGBPal1c0 6076
#define ringspriteSGBPal1c1 8935
#define ringspriteSGBPal1c2 6596
#define ringspriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ringspriteSGBPal2c0 6076
#define ringspriteSGBPal2c1 8935
#define ringspriteSGBPal2c2 6596
#define ringspriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ringspriteSGBPal3c0 6076
#define ringspriteSGBPal3c1 8935
#define ringspriteSGBPal3c2 6596
#define ringspriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ringspriteCGBPal0c0 32767
#define ringspriteCGBPal0c1 670
#define ringspriteCGBPal0c2 831
#define ringspriteCGBPal0c3 21503

/* Gameboy Color palette 1 */
#define ringspriteCGBPal1c0 6076
#define ringspriteCGBPal1c1 8935
#define ringspriteCGBPal1c2 6596
#define ringspriteCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define ringspriteCGBPal2c0 6076
#define ringspriteCGBPal2c1 8935
#define ringspriteCGBPal2c2 6596
#define ringspriteCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define ringspriteCGBPal3c0 6076
#define ringspriteCGBPal3c1 8935
#define ringspriteCGBPal3c2 6596
#define ringspriteCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define ringspriteCGBPal4c0 6076
#define ringspriteCGBPal4c1 8935
#define ringspriteCGBPal4c2 6596
#define ringspriteCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define ringspriteCGBPal5c0 6076
#define ringspriteCGBPal5c1 8935
#define ringspriteCGBPal5c2 6596
#define ringspriteCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define ringspriteCGBPal6c0 6076
#define ringspriteCGBPal6c1 8935
#define ringspriteCGBPal6c2 6596
#define ringspriteCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define ringspriteCGBPal7c0 6076
#define ringspriteCGBPal7c1 8935
#define ringspriteCGBPal7c2 6596
#define ringspriteCGBPal7c3 5344

/* CGB palette entries. */
#define ringspriteCGB0 0
#define ringspriteCGB1 0
#define ringspriteCGB2 0
#define ringspriteCGB3 0
/* Start of tile array. */
extern const unsigned char ringsprite[];

#endif

/* End of EXPORT.H */
