/*

 WINMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\grafika.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __winmap_h_INCLUDE
#define __winmap_h_INCLUDE

#define windowsWidth 20
#define windowsHeight 3
#define windowsBank 0

#define windows windowsPLN0
extern const unsigned char windowsPLN0[];

#endif

/* End of WINMAP.H */
