/*

 EMPTY_ROTATED.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define empty_rotatedWidth 3
#define empty_rotatedHeight 3
#define empty_rotatedBank 0

#define empty_rotated empty_rotatedPLN0
const unsigned char empty_rotatedPLN0[] =
{
  0x1D,0x1E,0x1F,0x20,0x21,0x1C,0x00,0x15,0x16
};

const unsigned char empty_rotatedPLN1[] =
{
  0x01,0x01,0x01,0x01,0x01,0x01,0x02,0x07,0x01
};

/* End of EMPTY_ROTATED.C */
