/*

 SONIC_ROTATED.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\GAMEBOY\projekty\SonicGB\nastroje\sprity.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define sonic_rotatedWidth 3
#define sonic_rotatedHeight 3
#define sonic_rotatedBank 0

#define sonic_rotated sonic_rotatedPLN0
const unsigned char sonic_rotatedPLN0[] =
{
  0x10,0x0F,0x0E,0x13,0x12,0x11,0x16,0x15,0x00
};

const unsigned char sonic_rotatedPLN1[] =
{
  0x21,0x21,0x21,0x21,0x21,0x21,0x21,0x27,0x02
};

/* End of SONIC_ROTATED.C */
