//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_moto_red_H
#define METASPRITE_moto_red_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define moto_red_TILE_ORIGIN 0
#define moto_red_TILE_W 8
#define moto_red_TILE_H 8
#define moto_red_WIDTH 16
#define moto_red_HEIGHT 16
#define moto_red_TILE_COUNT 4
#define moto_red_PALETTE_COUNT 1
#define moto_red_COLORS_PER_PALETTE 4
#define moto_red_TOTAL_COLORS 4
#define moto_red_PIVOT_X 8
#define moto_red_PIVOT_Y 8
#define moto_red_PIVOT_W 16
#define moto_red_PIVOT_H 16

BANKREF_EXTERN(moto_red)

extern const palette_color_t moto_red_palettes[4];
extern const uint8_t moto_red_tiles[64];

extern const metasprite_t* const moto_red_metasprites[1];

#endif
