//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ryba_H
#define METASPRITE_ryba_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ryba_TILE_ORIGIN 0
#define ryba_TILE_W 8
#define ryba_TILE_H 8
#define ryba_WIDTH 16
#define ryba_HEIGHT 16
#define ryba_TILE_COUNT 4
#define ryba_PALETTE_COUNT 1
#define ryba_COLORS_PER_PALETTE 4
#define ryba_TOTAL_COLORS 4
#define ryba_PIVOT_X 8
#define ryba_PIVOT_Y 8
#define ryba_PIVOT_W 16
#define ryba_PIVOT_H 16

BANKREF_EXTERN(ryba)

extern const palette_color_t ryba_palettes[4];
extern const uint8_t ryba_tiles[64];

extern const metasprite_t* const ryba_metasprites[1];

#endif
