/*

 GRAFIKA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 24

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __grafika_h_INCLUDE
#define __grafika_h_INCLUDE

/* Bank of tiles. */
#define TileLabelBank 0
/* CGBpalette entries. */
extern const unsigned char TileLabelCGB[];
/* Start of tile array. */
extern const unsigned char TileLabel[];

#endif

/* End of GRAFIKA.H */
