/*

 GRAFIKA_COMPRESSED.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 19

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __grafika_compressed_h_INCLUDE
#define __grafika_compressed_h_INCLUDE

/* Bank of tiles. */
#define TileLabelBank 0
/* CGBpalette entries. */
extern const unsigned char TileLabelCGB[];
/* Start of tile array. */
extern const unsigned char TileLabel[];

#endif

/* End of GRAFIKA_COMPRESSED.H */
