/*

 GREENHILL1_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 130 x 18
   Tile set      : grafika.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __greenhill1_map_h_INCLUDE
#define __greenhill1_map_h_INCLUDE

#define greenmapWidth 130
#define greenmapHeight 18
#define greenmapBank 0

#define greenmap greenmapPLN0
extern const unsigned char greenmapPLN0[];
extern const unsigned char greenmapPLN1[];

#endif

/* End of GREENHILL1_MAP.H */
