/*

Filename: 11.png_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 1 x 1
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define 11_map_width 1
#define 11_map_height 1
#define 11_map_tiles 1
#define 11_map_bytes 1

extern unsigned char 11_map[];
extern unsigned char 11_map_attr[];

