/*

Filename: 11.png_map.c 

Map SOURCE File 

 Info:
   Section       :
   Bank          : 0
   Map size      : 1 x 1
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define 11_map_width 1
#define 11_map_height 1
#define 11_map_tiles 1
#define 11_map_bytes 1


const unsigned char 11_map[1] = 
{
   0, };


const unsigned char 11_map_attr[1] = 
{
   0, };
